=== thraindk/web-exercises/XML_JSON/computer.xsd
<?xml version="1.0" encoding="utf-8"?>

<!-- xs ist Standard-Namespace mit Standard value -->
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">

<!-- eigene komplexe Datenstruktur -->
<xs:complexType name="computer">

    <xs:sequence>
        <xs:element name="name" type="xs:string"/>
        <xs:element name="cpu" type="xs:integer" minOccurs="0" maxOccurs="5000"/>
        <xs:element name="ram" type="xs:integer" minOccurs="0"/>
    </xs:sequence>

    <xs:attribute name="id" type="xs:integer"/>

</xs:complexType>

<!-- Definition Liste davon -->
<xs:element name="pc-liste">
    <xs:complexType>
        <xs:sequence>
            <xs:element name="pc" type="computer" maxOccurs="unbounded"/>
        </xs:sequence>
    </xs:complexType>
</xs:element>

</xs:schema>

=== thraindk/web-exercises/XML_JSON/PCs.xml
<?xml version="1.0" encoding="UTF-8"?>

<!-- keine eigener Namespace, xsd ist im gleichen Verzeichnis (sonst URL name.xsd)-->
<pc-liste xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
xsi:noNamespaceSchemaLocation="computer.xsd">

<!-- Datentypen in der pc-liste ist "pc" vom Typ "computer" (s. xsd) -->
    <pc>
        <name>DELL</name>
        <cpu>2100</cpu>
        <ram>4</ram>
    </pc>

    <pc>
        <name>LENOVO</name>
        <cpu>3200</cpu>
        <ram>16</ram>
        <!-- <hdd>512</hdd> ungÃ¼ltig, da nicht definiert -->
    </pc>

</pc-liste>
